import { VehicleType } from "./models/Vehicle";

export async function migrateVehicleServicesV2() {
  console.log("🛠️ Running vehicle services migration v2...");

  const vehicleServices = [
    {
      key: "motorcycle",
      freeServices: [
        {
          key: "standard_service",
          name: "Standard Service",
          desc: "Includes use of vehicle, fuel, basic loading/unloading within 10 minutes waiting time, driver service, and standard route. Parking and toll fees are separate.",
          price: 0,
          unit: "per booking",
          isQuantifiable: false,
          isActive: true,
        },
      ],
      paidServices: [
        {
          key: "thermal_bag",
          name: "Thermal Bag",
          desc: "Insulated thermal bag for temperature-sensitive shipments to maintain product quality during transport",
          price: 50,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "extra_waiting_time",
          name: "Extra Waiting Time",
          desc: "Additional waiting time beyond the standard 10 minutes, up to 30 minutes",
          price: 30,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "buy_for_me",
          name: "Buy For Me (Purchase Service)",
          desc: "Driver will purchase items for you at the pickup location (up to ₱2,000 value)",
          price: 40,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "document_handling",
          name: "Document Handling",
          desc: "Special handling for important documents with extra care and secure packaging",
          price: 20,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "parking_fee",
          name: "Parking Fee",
          desc: "Reimbursement for parking fees incurred during pickup and delivery",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "toll_fee",
          name: "Toll Fee",
          desc: "Reimbursement for toll fees along the delivery route",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
      ],
    },
    {
      key: "sedan",
      freeServices: [
        {
          key: "standard_service",
          name: "Standard Service",
          desc: "Includes use of vehicle, fuel, driver service, standard loading/unloading within 15 meters and 10 minutes waiting time. Parking and toll fees are separate.",
          price: 0,
          unit: "per booking",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "customer_staff",
          name: "Customer Staff (Up to 2)",
          desc: "Allow up to 2 of your staff to ride along for administration or security purposes",
          price: 0,
          unit: "per booking",
          isQuantifiable: false,
          isActive: true,
        },
      ],
      paidServices: [
        {
          key: "extra_helper",
          name: "Extra Helper",
          desc: "Helper for loading, unloading, and carrying items",
          price: 200,
          unit: "per person",
          isQuantifiable: true,
          maxQuantity: 2,
          isActive: true,
        },
        {
          key: "extra_waiting_time",
          name: "Extra Waiting Time",
          desc: "Additional waiting time beyond the standard 10 minutes, up to 30 minutes",
          price: 40,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "special_help",
          name: "Special Help by Driver",
          desc: "Driver carries packages beyond 15 meters distance from vehicle",
          price: 60,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "aircon_required",
          name: "Aircon Required",
          desc: "Air-conditioned transport for temperature-sensitive items like food, flowers, or perishables",
          price: 100,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "ppe_kit",
          name: "PPE Kit",
          desc: "Personal Protective Equipment including masks, gloves, and hand sanitizer for safe handling",
          price: 50,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "first_aid_kit",
          name: "First Aid Kit",
          desc: "Basic first aid kit available during transport for emergencies",
          price: 75,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "parking_fee",
          name: "Parking Fee",
          desc: "Reimbursement for parking fees incurred during pickup and delivery",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "toll_fee",
          name: "Toll Fee",
          desc: "Reimbursement for toll fees along the delivery route",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
      ],
    },
    {
      key: "mpv_suv",
      freeServices: [
        {
          key: "standard_service",
          name: "Standard Service",
          desc: "Includes use of vehicle, fuel, driver service, standard loading/unloading within 15 meters and 15 minutes waiting time. Parking and toll fees are separate.",
          price: 0,
          unit: "per booking",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "customer_staff",
          name: "Customer Staff (Up to 2)",
          desc: "Allow up to 2 of your staff to ride along for administration or security purposes",
          price: 0,
          unit: "per booking",
          isQuantifiable: false,
          isActive: true,
        },
      ],
      paidServices: [
        {
          key: "extra_helper",
          name: "Extra Helper",
          desc: "Helper for loading, unloading, and carrying items",
          price: 200,
          unit: "per person",
          isQuantifiable: true,
          maxQuantity: 3,
          isActive: true,
        },
        {
          key: "extra_waiting_time",
          name: "Extra Waiting Time",
          desc: "Additional waiting time beyond the standard 10 minutes, up to 30 minutes",
          price: 45,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "special_help",
          name: "Special Help by Driver",
          desc: "Driver carries packages beyond 15 meters distance from vehicle",
          price: 60,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "aircon_required",
          name: "Aircon Required",
          desc: "Air-conditioned transport for temperature-sensitive items",
          price: 120,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "ppe_kit",
          name: "PPE Kit",
          desc: "Personal Protective Equipment including masks, gloves, and hand sanitizer for safe handling",
          price: 50,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "first_aid_kit",
          name: "First Aid Kit",
          desc: "Basic first aid kit available during transport for emergencies",
          price: 75,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "parking_fee",
          name: "Parking Fee",
          desc: "Reimbursement for parking fees incurred during pickup and delivery",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "toll_fee",
          name: "Toll Fee",
          desc: "Reimbursement for toll fees along the delivery route",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
      ],
    },
    {
      key: "light_van",
      freeServices: [
        {
          key: "standard_service",
          name: "Standard Service",
          desc: "Includes use of vehicle, fuel, driver service, standard loading/unloading within 15 meters and 15 minutes waiting time. Parking and toll fees are separate.",
          price: 0,
          unit: "per booking",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "customer_staff",
          name: "Customer Staff (Up to 2)",
          desc: "Allow up to 2 of your staff to ride along for administration or security purposes",
          price: 0,
          unit: "per booking",
          isQuantifiable: false,
          isActive: true,
        },
      ],
      paidServices: [
        {
          key: "extra_helper",
          name: "Extra Helper",
          desc: "Additional helper for loading, unloading, and carrying heavy items",
          price: 200,
          unit: "per person",
          isQuantifiable: true,
          maxQuantity: 4,
          isActive: true,
        },
        {
          key: "extra_waiting_time",
          name: "Extra Waiting Time",
          desc: "Additional waiting time beyond the standard 10 minutes, up to 30 minutes",
          price: 50,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "special_help",
          name: "Special Help by Driver",
          desc: "Driver carries packages beyond 15 meters distance from vehicle",
          price: 60,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "push_cart",
          name: "Push Cart",
          desc: "Use of push cart for easier transport of multiple items",
          price: 80,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "aircon_required",
          name: "Aircon Required",
          desc: "Air-conditioned transport for temperature-sensitive items",
          price: 150,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "ppe_kit",
          name: "PPE Kit",
          desc: "Personal Protective Equipment including masks, gloves, and hand sanitizer for safe handling",
          price: 50,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "first_aid_kit",
          name: "First Aid Kit",
          desc: "Basic first aid kit available during transport for emergencies",
          price: 75,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "parking_fee",
          name: "Parking Fee",
          desc: "Reimbursement for parking fees incurred during pickup and delivery",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "toll_fee",
          name: "Toll Fee",
          desc: "Reimbursement for toll fees along the delivery route",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
      ],
    },
    {
      key: "small_pickup",
      freeServices: [
        {
          key: "standard_service",
          name: "Standard Service",
          desc: "Includes use of vehicle, fuel, driver service, standard loading/unloading within 15 meters and 15 minutes waiting time. Parking and toll fees are separate.",
          price: 0,
          unit: "per booking",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "customer_staff",
          name: "Customer Staff (Up to 2)",
          desc: "Allow up to 2 of your staff to ride along for administration or security purposes",
          price: 0,
          unit: "per booking",
          isQuantifiable: false,
          isActive: true,
        },
      ],
      paidServices: [
        {
          key: "extra_helper",
          name: "Extra Helper",
          desc: "Additional helper for loading, unloading, and carrying heavy items",
          price: 200,
          unit: "per person",
          isQuantifiable: true,
          maxQuantity: 4,
          isActive: true,
        },
        {
          key: "extra_waiting_time",
          name: "Extra Waiting Time",
          desc: "Additional waiting time beyond the standard 10 minutes, up to 30 minutes",
          price: 50,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "special_help",
          name: "Special Help by Driver",
          desc: "Driver carries packages beyond 15 meters distance from vehicle",
          price: 60,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "rope_tie_down",
          name: "Rope & Tie-Down Service",
          desc: "Secure cargo with professional rope and tie-down equipment",
          price: 100,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "push_cart",
          name: "Push Cart",
          desc: "Use of push cart for easier transport of multiple items",
          price: 80,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "ppe_kit",
          name: "PPE Kit",
          desc: "Personal Protective Equipment including masks, gloves, and hand sanitizer for safe handling",
          price: 50,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "first_aid_kit",
          name: "First Aid Kit",
          desc: "Basic first aid kit available during transport for emergencies",
          price: 75,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "parking_fee",
          name: "Parking Fee",
          desc: "Reimbursement for parking fees incurred during pickup and delivery",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "toll_fee",
          name: "Toll Fee",
          desc: "Reimbursement for toll fees along the delivery route",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
      ],
    },
    {
      key: "l300",
      freeServices: [
        {
          key: "standard_service",
          name: "Standard Service",
          desc: "Includes use of vehicle, fuel, driver service, standard loading/unloading within 15 meters and 20 minutes waiting time. Parking and toll fees are separate.",
          price: 0,
          unit: "per booking",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "customer_staff",
          name: "Customer Staff (Up to 2)",
          desc: "Allow up to 2 of your staff to ride along for administration or security purposes",
          price: 0,
          unit: "per booking",
          isQuantifiable: false,
          isActive: true,
        },
      ],
      paidServices: [
        {
          key: "extra_helper",
          name: "Extra Helper",
          desc: "Additional helper for loading, unloading, and carrying heavy items",
          price: 200,
          unit: "per person",
          isQuantifiable: true,
          maxQuantity: 5,
          isActive: true,
        },
        {
          key: "extra_waiting_time",
          name: "Extra Waiting Time",
          desc: "Additional waiting time beyond the standard 10 minutes, up to 30 minutes",
          price: 55,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "special_help",
          name: "Special Help by Driver",
          desc: "Driver carries packages beyond 15 meters distance from vehicle",
          price: 60,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "rope_tie_down",
          name: "Rope & Tie-Down Service",
          desc: "Secure cargo with professional rope and tie-down equipment",
          price: 120,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "assembly_disassembly",
          name: "Assembly/Disassembly",
          desc: "Furniture assembly or disassembly service",
          price: 300,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "push_cart",
          name: "Push Cart",
          desc: "Use of push cart for easier transport of bulky items",
          price: 100,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "ppe_kit",
          name: "PPE Kit",
          desc: "Personal Protective Equipment including masks, gloves, and hand sanitizer for safe handling",
          price: 50,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "first_aid_kit",
          name: "First Aid Kit",
          desc: "Basic first aid kit available during transport for emergencies",
          price: 75,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "parking_fee",
          name: "Parking Fee",
          desc: "Reimbursement for parking fees incurred during pickup and delivery",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "toll_fee",
          name: "Toll Fee",
          desc: "Reimbursement for toll fees along the delivery route",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
      ],
    },
    {
      key: "closed_van",
      freeServices: [
        {
          key: "standard_service",
          name: "Standard Service",
          desc: "Includes use of vehicle, fuel, driver service, standard loading/unloading within 15 meters and 20 minutes waiting time. Parking and toll fees are separate.",
          price: 0,
          unit: "per booking",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "helper_included",
          name: "1 Helper Included",
          desc: "One helper included for loading and unloading assistance",
          price: 0,
          unit: "per booking",
          isQuantifiable: false,
          isActive: true,
        },
      ],
      paidServices: [
        {
          key: "extra_helper",
          name: "Extra Helper",
          desc: "Additional helper beyond the 1 included for loading, unloading, and carrying heavy items",
          price: 450,
          unit: "per person",
          isQuantifiable: true,
          maxQuantity: 5,
          isActive: true,
        },
        {
          key: "extra_waiting_time",
          name: "Extra Waiting Time",
          desc: "Additional waiting time beyond the standard 10 minutes, up to 30 minutes",
          price: 60,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "assembly_disassembly",
          name: "Assembly/Disassembly",
          desc: "Furniture assembly or disassembly service",
          price: 350,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "rope_tie_down",
          name: "Rope & Tie-Down Service",
          desc: "Secure cargo with professional rope and tie-down equipment",
          price: 150,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "push_cart",
          name: "Push Cart",
          desc: "Use of push cart for easier transport of bulky or heavy items",
          price: 120,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "protective_wrapping",
          name: "Protective Wrapping",
          desc: "Extra protective wrapping for fragile or valuable items",
          price: 200,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "ppe_kit",
          name: "PPE Kit",
          desc: "Personal Protective Equipment including masks, gloves, and hand sanitizer for safe handling",
          price: 50,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "first_aid_kit",
          name: "First Aid Kit",
          desc: "Basic first aid kit available during transport for emergencies",
          price: 75,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "parking_fee",
          name: "Parking Fee",
          desc: "Reimbursement for parking fees incurred during pickup and delivery",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "toll_fee",
          name: "Toll Fee",
          desc: "Reimbursement for toll fees along the delivery route",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
      ],
    },
    {
      key: "wing_van",
      freeServices: [
        {
          key: "standard_service",
          name: "Standard Service",
          desc: "Includes use of vehicle, fuel, driver service, standard loading/unloading within 15 meters and 20 minutes waiting time. Parking and toll fees are separate.",
          price: 0,
          unit: "per booking",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "helper_included",
          name: "1 Helper Included",
          desc: "One helper included for loading and unloading assistance",
          price: 0,
          unit: "per booking",
          isQuantifiable: false,
          isActive: true,
        },
      ],
      paidServices: [
        {
          key: "extra_helper",
          name: "Extra Helper",
          desc: "Additional helper beyond the 1 included for loading, unloading, and carrying heavy items",
          price: 450,
          unit: "per person",
          isQuantifiable: true,
          maxQuantity: 5,
          isActive: true,
        },
        {
          key: "extra_waiting_time",
          name: "Extra Waiting Time",
          desc: "Additional waiting time beyond the standard 10 minutes, up to 30 minutes",
          price: 60,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "assembly_disassembly",
          name: "Assembly/Disassembly",
          desc: "Furniture assembly or disassembly service",
          price: 350,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "rope_tie_down",
          name: "Rope & Tie-Down Service",
          desc: "Secure cargo with professional rope and tie-down equipment",
          price: 150,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "push_cart",
          name: "Push Cart",
          desc: "Use of push cart for easier transport of bulky or heavy items",
          price: 120,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "side_loading",
          name: "Side Wing Loading",
          desc: "Easy side access loading for oversized or bulky items",
          price: 100,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "protective_wrapping",
          name: "Protective Wrapping",
          desc: "Extra protective wrapping for fragile or valuable items",
          price: 200,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "ppe_kit",
          name: "PPE Kit",
          desc: "Personal Protective Equipment including masks, gloves, and hand sanitizer for safe handling",
          price: 50,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "first_aid_kit",
          name: "First Aid Kit",
          desc: "Basic first aid kit available during transport for emergencies",
          price: 75,
          unit: "per service",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "parking_fee",
          name: "Parking Fee",
          desc: "Reimbursement for parking fees incurred during pickup and delivery",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
        {
          key: "toll_fee",
          name: "Toll Fee",
          desc: "Reimbursement for toll fees along the delivery route",
          price: 0,
          unit: "actual cost",
          isQuantifiable: false,
          isActive: true,
        },
      ],
    },
  ];

  for (const vehicle of vehicleServices) {
    await VehicleType.updateOne(
      { key: vehicle.key },
      {
        $set: {
          freeServices: vehicle.freeServices,
          paidServices: vehicle.paidServices,
        },
      }
    );
    console.log(`✓ Updated services for ${vehicle.key}`);
  }

  console.log("✅ Vehicle services migration v2 completed");
}
